#===================================================================
# SwiftLint Configuration
# See https://realm.github.io/SwiftLint/rule-directory.html for rule details
#===================================================================

#-------------------------------------------------------------------
# Project-Specific Placeholders
#-------------------------------------------------------------------
# Replace the placeholders with values that match your project.

# Paths to include in linting
included:
  - CounterApp/**/*.swift
  - CounterAppTests/**/*.swift
  - CounterAppUITests/**/*.swift
  - InteractiveCounterWidget/**/*.swift
  - ICUserDefaultsManager/**/*.swift

#-------------------------------------------------------------------
# Analysis Targets
#-------------------------------------------------------------------
excluded:
  - .git
  - .build
  - DerivedData
  - .github
  - Carthage
  - build
  - xcbuild
  - "**/*.generated.swift"
  - "**/*.xcodeproj"

#-------------------------------------------------------------------
# Rule Configuration
#-------------------------------------------------------------------
disabled_rules:
  - trailing_whitespace # 行末の空白を許可
  - line_length # 行の長さは別途カスタマイズ
  - trailing_newline # 末尾の改行を無視
  - trailing_comma # SwiftFormatで制御するため無効化
  - missing_docs # 公開APIのドキュメント要求を無効化
  - opening_brace # 波括弧の配置ルールを無効化
  - multiple_closures_with_trailing_closure # 複数のクロージャを持つ場合のトレイリングクロージャ構文を許可
  - function_body_length # 関数本体の長さ制限を無効化
  - type_body_length # 型定義の長さ制限を無効化
  - empty_count # count プロパティの特定パターンが誤検出されるため無効化

opt_in_rules:
  - force_unwrapping # 強制アンラップを禁止
  - sorted_imports # importを整列
  - vertical_whitespace # 垂直方向の空白行を整理
  - explicit_init # すべての init を明示的に記述
  - first_where # filter { ... }.first より first(where:) を推奨
  - toggle_bool # foo = !foo よりも foo.toggle() を推奨

analyzer_rules:
  - unused_declaration # 未使用宣言の検出
  - unused_import # 未使用importの検出
  - explicit_self # プロパティやメソッド参照時に self. を明示
  - redundant_nil_coalescing # 不要な ?? nil の検出

#-------------------------------------------------------------------
# Individual Rule Settings
#-------------------------------------------------------------------

# ファイルの長さの制限
file_length:
  warning: 600
  error: 1000

# 循環的複雑度の制限 - if/switch/for などの分岐やループの総数で算出
cyclomatic_complexity:
  warning: 10
  error: 20

# ネストの制限
nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

# 識別子 (変数名、定数名など) の命名規則
identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - URL
    - x
    - y
    - i
    - to
    - at
    - of
    - from
    - with

# switch文のcaseのアライメント - SwiftFormatと一致させる
switch_case_alignment:
  indented_cases: true

#-------------------------------------------------------------------
# Output Settings
#-------------------------------------------------------------------
reporter: "emoji"
