# mint run xcodegen

name: CounterApp
options:
  bundleIdPrefix: com.akitorahayashi
  createIntermediateGroups: true
  defaultConfig: Debug

packages:
  ICUserDefaultsManager:
    path: ICUserDefaultsManager
    schemeGenerationMode: none
  
settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
  IPHONEOS_DEPLOYMENT_TARGET: 17.0
  SWIFT_VERSION: 5.0

configs:
  Debug: debug
  Release: release

targets:
  CounterApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - CounterApp
    dependencies:
      - target: InteractiveCounterWidget
        embed: true
      - package: ICUserDefaultsManager
        product: ICUserDefaultsManager
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.InteractiveCounterApp
      INFOPLIST_FILE: CounterApp/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      DEVELOPMENT_ASSET_PATHS: CounterApp/Resources
      ENABLE_PREVIEWS: YES
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_ENTITLEMENTS: CounterApp/CounterAppEntitlements.entitlements

  InteractiveCounterWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - InteractiveCounterWidget
    dependencies:
      - package: ICUserDefaultsManager
        product: ICUserDefaultsManager
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.InteractiveCounterApp.widget
      INFOPLIST_FILE: InteractiveCounterWidget/Info.plist
      SKIP_INSTALL: YES
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_ENTITLEMENTS: InteractiveCounterWidget/InteractiveCounterWidgetEntitlements.entitlements

  CounterAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - CounterAppTests
    dependencies:
      - target: CounterApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.InteractiveCounterApp.tests
      INFOPLIST_FILE: CounterAppTests/Info.plist

  CounterAppUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - CounterAppUITests
    dependencies:
      - target: CounterApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.InteractiveCounterApp.uitests
      INFOPLIST_FILE: CounterAppUITests/Info.plist

schemes:
  CounterApp:
    build:
      targets:
        CounterApp: all
        InteractiveCounterWidget: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - CounterAppTests
        - CounterAppUITests
    archive:
      config: Release

  CounterAppTests:
    build:
      targets:
        CounterAppTests: all
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - CounterAppTests

  CounterAppUITests:
    build:
      targets:
        CounterAppUITests: all
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - CounterAppUITests

