name: Format and Lint

on:
  workflow_call:

jobs:
  format-and-lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Mint
      run: brew install mint

    - name: Run SwiftFormat
      run: mint run swiftformat .

    - name: Run SwiftLint
      run: mint run swiftlint --strict

    - name: Check for changes
      id: check
      run: |
        git diff --exit-code && echo "FORMAT_OK=true" >> $GITHUB_ENV || echo "FORMAT_OK=false" >> $GITHUB_ENV