name: Setup Mint Dependencies

on:
  workflow_call:

jobs:
  setup:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Mint
        run: brew install mint

      - name: Bootstrap Mint packages
        run: mint bootstrap